
export const categories = [
    { id: "all", name: "All Products", icon: "🛒" },
    { id: "streaming", name: "Streaming", icon: "🎬" },
    { id: "music", name: "Music", icon: "🎵" },
    { id: "design", name: "Design", icon: "🎨" },
    { id: "productivity", name: "Productivity", icon: "🛠️" },
    { id: "games", name: "Games", icon: "🎮" },
];

export const products = [
    {
        id: 1,
        title: "Netflix UHD 4K (1 Bulan)",
        price: "Rp 35.000",
        originalPrice: "Rp 186.000",
        features: ["4K Ultra HD Quality", "Private Profile", "Full Garansi 30 Hari", "Bisa Login di HP/TV/Laptop"],
        isBestSeller: true,
        category: "Streaming",
        imageColor: "bg-gradient-to-br from-red-600 to-black",
        image: "/products/netflix.png",
    },
    {
        id: 2,
        title: "Spotify Premium (Individu)",
        price: "Rp 25.000",
        originalPrice: "Rp 55.000",
        features: ["No Ads (Bebas Iklan)", "Download Musik Offline", "Bisa Akun Lama/Baru", "Garansi Full 1 Bulan"],
        isBestSeller: true,
        category: "Music",
        imageColor: "bg-gradient-to-br from-green-500 to-black",
        image: "/products/spotify.png",
    },
    {
        id: 3,
        title: "Canva Pro Team (Lifetime)",
        price: "Rp 20.000",
        originalPrice: "Rp 150.000",
        features: ["Unlock Semua Aset Premium", "Font & Template Pro", "Magic Resize", "Garansi 1 Tahun"],
        isBestSeller: false,
        category: "Design",
        imageColor: "bg-gradient-to-br from-cyan-400 to-purple-600",
        image: "/products/canva.png",
    },
    {
        id: 4,
        title: "YouTube Premium Alt",
        price: "Rp 15.000",
        originalPrice: "Rp 59.000",
        features: ["No Ads Video", "Background Play", "YouTube Music Premium", "Garansi 1 Bulan"],
        isBestSeller: false,
        category: "Streaming",
        imageColor: "bg-gradient-to-br from-red-500 to-red-900",
        image: "/products/youtube.png",
    },
    {
        id: 5,
        title: "ChatGPT Plus (Shared)",
        price: "Rp 50.000",
        originalPrice: "Rp 300.000",
        features: ["Akses GPT-4", "Browsing & Plugins", "Response Cepat", "Shared Account"],
        isBestSeller: true,
        category: "Productivity",
        imageColor: "bg-gradient-to-br from-green-400 to-teal-800",
        image: "/products/chatgpt.png",
    },
    {
        id: 6,
        title: "Disney+ Hotstar (Shared)",
        price: "Rp 20.000",
        originalPrice: "Rp 65.000",
        features: ["4K Support", "All Movies & Series", "Language Indonesia", "Garansi Full"],
        isBestSeller: false,
        category: "Streaming",
        imageColor: "bg-gradient-to-br from-blue-700 to-blue-900",
        image: "/products/disney.png",
    },
];
